export const postsRequestTypes = {
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS'
};

export const usersRequestTypes = {
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS'
};